### ISSUE TITLE
压缩后上传7牛服务器  播放不了

### ISSUE THREAD

**Issue by skill20** [wuxiaoqiang625/VideoCompress#11]
压缩后上传到7牛服务器，在本地压缩的视频可以播放，
但是拿到服务器的视频地址是播放不了，一直在缓冲，有遇到过吗

**Comment by wuxiaoqiang625** [comment]
本地压缩后上传到服务器播放不了，你看下服务器那边地址是不是有问题，或者地址发来看下

**Comment by skill20** [comment]
下面是ffmpeg对视频信息的提取：
（压缩前的）Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 12082 kb/s, SAR 1:1 DAR 16:9, 30.19 fps, 30 tbr, 90k tbn, 60 tbc (default)
（压缩后）Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p, 720x1280, 572 kb/s, 30.19 fps, 30 tbr, 90k tbn, 50 tbc (default)

使用的分辨率是原来的分辨率 码率是450K

播放的时候一直在缓冲中

**Comment by wuxiaoqiang625** [comment]
你是用的FFmpeg压缩的？，我这个是硬解的。。。FFmpeg没仔细去了解。。。。

**Comment by skill20** [comment]
用的这个框架，用ffmpeg检测的视频信息

**Comment by skill20** [comment]
用的这个框架，用ffmpeg检测的视频信息

**Comment by skill20** [comment]
Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p, 720x1280 [SAR 1:1 DAR 9:16], 774 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
  
这个是ffmpeg 压缩后提取的信息

你压缩后的视频上传服务器后，通过网络地址能播放不？

**Comment by wuxiaoqiang625** [comment]
。。。表示看不懂FFmpeg,你现在的问题本地可以播放服务器端获取的是播放不了，说明问题不存在于本地，你传到服务器是不是有什么地方没弄对，或者你把视频链接发下，我看下

**Comment by skill20** [comment]
http://p6jtfbpem.bkt.clouddn.com/bcecba57963e4dc38638075050f34c3b
这个是网络地址，
用浏览器播放是可以播放的。

**Comment by wuxiaoqiang625** [comment]
那没问题呀。。。你app写的播放器播放不了？

**Comment by wuxiaoqiang625** [comment]
或者你加我QQ把1053591833 。。。这上面说不清

**Comment by skill20** [comment]
是的，不止android的播放不了，ios的也是一直在缓冲中，
初步判断是不是视频每秒的数据太大了

其实不压缩也是播放不了的，就是手机自拍后上传服务器，也是一直缓冲。

**Comment by wuxiaoqiang625** [comment]
问了半天。。。最后的答案是，ijk播放器转码问题。。。。。。
