### ISSUE TITLE
网络上下载的MP4视频压缩不了

### ISSUE THREAD

**Issue by 06304322** [wuxiaoqiang625/VideoCompress#14]
我下了一个6M的视频压缩出来只有140B，而且播放不了，播放错误。又下载了一个也是同样的结果。

**Comment by wuxiaoqiang625** [comment]
你可以用本地手机试下。。。网络上的视频格式不一定对

**Comment by 06304322** [comment]
压缩之前是可以正常播放的

**Comment by wuxiaoqiang625** [comment]
首先 不管能不能播放的问题，你用demo搜下本地压缩可不可以，如果本地压缩可以那就没问题，如果本地不行那我这个就有问题。。。

**Comment by 06304322** [comment]
用demo试了也是不行。

**Comment by wuxiaoqiang625** [comment]
你压缩的视频 是多大的，还有你选择大点的视频压缩试下，不行是怎么个不行的。。可以加我QQ1053591833，发个截图或者视频看下

**Comment by wuxiaoqiang625** [comment]
视频是被压缩过的，在压缩就出现问题。。。
